apiVersion: config.supervisor.pinniped.dev/v1alpha1
kind: FederationDomain
metadata:
  name: pinniped-provider
  namespace: pinniped-supervisor
spec:
  issuer: ${OIDC_SUP_ISSUER}
  tls:
    secretName: fed-tls-cert-secret
