---
apiVersion: v1
kind: Secret
metadata:
  namespace: pinniped-supervisor
  name: ${OIDC_PROVIDER}-client-credentials
type: secrets.pinniped.dev/oidc-client
stringData:
  clientID: "${CLIENT_ID}"
  clientSecret: "${CLIENT_SECRET}"
