---
apiVersion: idp.supervisor.pinniped.dev/v1alpha1
kind: OIDCIdentityProvider
metadata:
  namespace: pinniped-supervisor
  name: ${OIDC_PROVIDER}
spec:
  issuer: ${OIDC_ISSUER}
  claims:
    username: email
    groups: groups
  authorizationConfig:
    additionalScopes: ['email']
  client:
    secretName: ${OIDC_PROVIDER}-client-credentials
