apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
   name: tkg-jwt-authenticator
spec:
   issuer: https://dev-xxxxxx.okta.com/oauth2/default
   audience: xxsfsdfsdffsdfsdf
   claims:
    username: email
    groups: groups
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pinniped-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: navneetv@vmware.com
